// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (name, description, price, category_id, stock, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, description, price, category_id, stock, is_active, created_at, updated_at
`

type CreateProductParams struct {
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Stock       int32          `json:"stock"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CategoryID,
		arg.Stock,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.Stock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, description, price, category_id, stock, is_active, created_at, updated_at
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.Stock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, description, price, category_id, stock, is_active, created_at, updated_at
FROM products
WHERE
    ($1::text = '' OR name ILIKE '%' || $1 || '%')
    AND ($2::uuid IS NULL OR category_id = $2)
    AND ($3::text = '' OR is_active = ($3::text = 'true'))
    AND ($4::integer = 0 OR stock >= $4)
    AND ($5::numeric IS NULL OR price >= $5)
    AND ($6::numeric IS NULL OR price <= $6)
    AND ($7::timestamptz IS NULL OR created_at < $7)
ORDER BY created_at DESC
LIMIT $8
`

type ListProductsParams struct {
	Column1 string             `json:"column_1"`
	Column2 pgtype.UUID        `json:"column_2"`
	Column3 string             `json:"column_3"`
	Column4 int32              `json:"column_4"`
	Column5 pgtype.Numeric     `json:"column_5"`
	Column6 pgtype.Numeric     `json:"column_6"`
	Column7 pgtype.Timestamptz `json:"column_7"`
	Limit   int32              `json:"limit"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CategoryID,
			&i.Stock,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = COALESCE(NULLIF($2, ''), name),
    description = $3,
    price = $4,
    category_id = $5,
    stock = $6,
    is_active = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, price, category_id, stock, is_active, created_at, updated_at
`

type UpdateProductParams struct {
	ID          pgtype.UUID    `json:"id"`
	Column2     interface{}    `json:"column_2"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	Stock       int32          `json:"stock"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Column2,
		arg.Description,
		arg.Price,
		arg.CategoryID,
		arg.Stock,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CategoryID,
		&i.Stock,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
